import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/components/ThemeProvider";
import { cn } from "@/lib/utils";
import AuthProvider from "@/lib/components/auth/AuthProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Lora({ subsets: ["latin"], weight: "variable" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="it" suppressHydrationWarning>
			<body
				className={cn(inter.className, "text-stone-800 bg-stone-200")}>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					disableTransitionOnChange>
					<AuthProvider>
						{children}
						<Toaster />
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
